// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {openems} from '../models';
import {solarforecast} from '../models';
import {config} from '../models';

export function CallOpenEmsApi(arg1:string,arg2:string,arg3:any):Promise<openems.Response>;

export function GetClearSkyForecast():Promise<Array<solarforecast.Forecast>>;

export function GetConfig():Promise<config.Config>;

export function GetSolarForecast():Promise<Array<solarforecast.Forecast>>;

export function SaveConfig(arg1:config.Config):Promise<void>;
