// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallOpenEmsApi(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallOpenEmsApi'](arg1, arg2, arg3);
}

export function GetClearSkyForecast() {
  return window['go']['main']['App']['GetClearSkyForecast']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSolarForecast() {
  return window['go']['main']['App']['GetSolarForecast']();
}

export function GetSolarForecastConfig() {
  return window['go']['main']['App']['GetSolarForecastConfig']();
}

export function IsSolarForecastInitialized() {
  return window['go']['main']['App']['IsSolarForecastInitialized']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetSolarForecastConfig(arg1) {
  return window['go']['main']['App']['SetSolarForecastConfig'](arg1);
}
