// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {solarforecast} from '../models';
import {openems} from '../models';
import {time} from '../models';

export function GetClearSkyForecast():Promise<Array<solarforecast.Forecast>>;

export function GetComponentConfigurations():Promise<Record<string, openems.Component>>;

export function GetSolarForecast():Promise<Array<solarforecast.Forecast>>;

export function GetSystemUpdateState():Promise<any>;

export function QueryHistoricData(arg1:time.Time,arg2:time.Time,arg3:string,arg4:Array<string>,arg5:number,arg6:string):Promise<openems.HistoricTimeseries>;

export function QueryHistoricEnergyPerPeriod(arg1:time.Time,arg2:time.Time,arg3:string,arg4:Array<string>,arg5:number,arg6:string):Promise<openems.HistoricTimeseries>;

export function ReadBatteries():Promise<Array<openems.Battery>>;

export function ReadComponent(arg1:string):Promise<Array<openems.ChannelItem>>;
