name: Build Release
on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  builder-linux:
    strategy:
      matrix:
        os: [ ubuntu ]
        arch: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}${{ matrix.arch == 'arm64' && '-arm' || '-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          architecture: ${{ matrix.arch }}
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev build-essential
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          cd ..
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor
          mkdir artifacts
      - name: Build Application
        run: |
          wails build -platform linux/${{ matrix.arch }} -o oad -tags webkit2_41
      - name: Package Application (linux/${{ matrix.arch }})
        run: |
          tar cvfz artifacts/oad_linux_${{ matrix.arch }}.tar.gz build/bin/*
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}_${{ matrix.goos }}_${{ matrix.arch }}
          path: artifacts/*

  builder-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        architecture: ${{ matrix.arch }}
    - name: Setup Node
      uses: actions/setup-node@v4
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        cd ..
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        wails doctor
        mkdir artifacts
    - name: Build Application (darwin/arm64)
      run: |
        wails build -platform darwin/arm64 -clean
    - name: Package Application (darwin/arm64)
      run: |
        tar cvfz artifacts/oad_darwin_arm64.tar.gz build/bin/*
    - name: Build Application (darwin/universal)
      run: |
        wails build -platform darwin/universal -clean
    - name: Package Application (darwin/arm64)
      run: |
        tar cvfz artifacts/oad_darwin_universal.tar.gz build/bin/*
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}_${{ matrix.goos }}_${{ matrix.arch }}
        path: artifacts/*

  builder-windows:
    strategy:
      matrix:
        os: [ windows ]
        arch: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}${{ matrix.arch == 'arm64' && '-arm' || '-11-latest' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        architecture: ${{ matrix.arch }}
    - name: Setup Node
      uses: actions/setup-node@v4
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        cd ..
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        wails doctor
    - name: Build Application
      run: |
        wails build -platform windows/${{ matrix.arch }}
    - name: Package Application (windows/${{ matrix.arch }})
      run: |
        zip artifacts/oad_windows_${{ matrix.arch }}.zip build/bin/*
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}_${{ matrix.goos }}_${{ matrix.arch }}
        path: artifacts/*

  upload-to-release:
    name: Attach assets to release
    needs:
      - builder-linux
      - builder-macos
      - builder-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List packaged files
        run: ls -la dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*               # attaches to the release that triggered this workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
