name: Build Release
on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  builder-linux:
    strategy:
      matrix:
        os: [ ubuntu ]
        arch: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}${{ matrix.arch == 'arm64' && '-arm' || '-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          architecture: ${{ matrix.arch }}
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev build-essential
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          cd ..
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor
      - name: Build Application
        run: |
          wails build -o oad
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

  builder-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        architecture: ${{ matrix.arch }}
    - name: Setup Node
      uses: actions/setup-node@v4
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        cd ..
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        wails doctor
    - name: Build Application
      run: |
        wails build -platform darwin/arm64 -o "OpenEMS Advanced Dashboard.app"
        wails build -platform darwin/universal -o "OpenEMS Advanced Dashboard (universal).app"
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}_${{ matrix.goos }}_${{ matrix.arch }}
        path: build/bin/*

  builder-windows:
    strategy:
      matrix:
        os: [ windows ]
        arch: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}${{ matrix.arch == 'arm64' && '-arm' || '-11-latest' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        architecture: ${{ matrix.arch }}
    - name: Setup Node
      uses: actions/setup-node@v4
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        cd ..
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        wails doctor
    - name: Build Application
      run: |
        wails build -o "OpenEMS Advanced Dashboard.exe"
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}_${{ matrix.goos }}_${{ matrix.arch }}
        path: build/bin/*

  upload-to-release:
    name: Attach assets to release
    needs:
      - builder-linux
      - builder-macos
      - builder-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List packaged files
        run: ls -la dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*               # attaches to the release that triggered this workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
